apiVersion: v1
kind: Service
metadata:
  annotations:
    io.elastest.type: core
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: edm
  name: edm
spec:
  ports:
  - name: "37003"
    port: 37003
    targetPort: 8080
  selector:
    io.kompose.service: edm
status:
  loadBalancer: {}
