---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edm-elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        elastest-service: edm-elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx1g -Xms1g
        - name: discovery.type
          value: single-node
        image: elastest/edm-elasticsearch:latest
        name: edm-elasticsearch
        volumeMounts:
        - mountPath: /backup
          name: esbackup
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
      hostname: edm-elasticsearch
      volumes:
      - name: esbackup
        persistentVolumeClaim:
          claimName: edm-es-backup
      - name: esdata
        persistentVolumeClaim:
          claimName: edm-es-data

---
apiVersion: v1
kind: Service
metadata:
  name: edm-elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    elastest-service: edm-elasticsearch
  type: ClusterIP
