---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edm-kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        elastest-service: edm-kibana
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        - name: discovery.type
          value: zen
        - name: discovery.zen.ping.unicast.hosts
          value: edm-elasticsearch
        image: elastest/edm-kibana:latest
        name: edm-kibana
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: edm-kibana-config
          subPath: kibana.yml
      volumes:
      - name: edm-kibana-config
        configMap:
          name: edm-kibana-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  edm-kibana-config
data:
    kibana.yml: |
      ---
      ## Default Kibana configuration from kibana-docker.
      ## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
      #
      server.name: edm-kibana
      server.host: "0"
      elasticsearch.url: http://edm-elasticsearch:9200

      ## Disable X-Pack
      ## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      ##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      #
      xpack.security.enabled: false
      xpack.monitoring.enabled: false
      xpack.ml.enabled: false
      xpack.graph.enabled: false
      xpack.reporting.enabled: false


---
apiVersion: v1
kind: Service
metadata:
  name: edm-kibana
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
  selector:
    elastest-service: edm-kibana
  type: LoadBalancer
