apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sparkmaster
  name: sparkmaster
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "7077"
    port: 7077
    targetPort: 7077
  selector:
    io.kompose.service: sparkmaster
status:
  loadBalancer: {}
